spring.application.name=student-course-api
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/course_management
spring.datasource.username=courseDB
spring.datasource.password=pro@123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080